import base64
import logging
from io import BytesIO
from typing import Optional

from google import genai
from PIL import Image

from app.models.image import ImageGenerationRequest, ImageGenerationResponse

log = logging.getLogger(__name__)


class ImageService:
    def __init__(self):
        self.client = genai.Client()
        self.model = "gemini-2.0-flash-exp"

    async def generate_image(
        self, input: ImageGenerationRequest
    ) -> ImageGenerationResponse:
        """
        Generate an image using Google's Gemini API.
        
        Args:
            input: The image generation request containing prompt and optional input image
            
        Returns:
            ImageGenerationResponse containing the generated image data
        """
        log.info(f"Generating image with prompt: {input.prompt}")
        
        # Prepare the content list
        contents = [input.prompt]
        
        # If there's input image data, decode it and add to contents
        if input.image_data:
            try:
                image_bytes = base64.b64decode(input.image_data)
                image = Image.open(BytesIO(image_bytes))
                contents.append(image)
                log.info("Added input image to request")
            except Exception as e:
                log.error(f"Error decoding input image: {e}")
                raise ValueError(f"Invalid image data: {e}")
        
        # Call Gemini API
        try:
            response = self.client.models.generate_content(
                model=self.model,
                contents=contents,
            )
            
            # Process response
            text_response: Optional[str] = None
            generated_image_data: Optional[str] = None
            
            for part in response.candidates[0].content.parts:
                if part.text is not None:
                    text_response = part.text
                    log.info(f"Received text response: {text_response}")
                elif part.inline_data is not None:
                    # Convert image to base64
                    image = Image.open(BytesIO(part.inline_data.data))
                    buffered = BytesIO()
                    image.save(buffered, format="PNG")
                    generated_image_data = base64.b64encode(buffered.getvalue()).decode('utf-8')
                    log.info("Generated image received and encoded")
            
            if not generated_image_data:
                log.error("No image data received from Gemini API")
                raise ValueError("No image generated by the model")
            
            return ImageGenerationResponse(
                image_data=generated_image_data,
                text_response=text_response
            )
            
        except Exception as e:
            log.error(f"Error calling Gemini API: {e}")
            raise RuntimeError(f"Failed to generate image: {e}")

